name: 'modules markdown file updater'
description: 'modules markdown file updater'
inputs:
  template_markdown_file:
    description: 'template markdown file'
    required: true
outputs:
  markdown:
    description: mardown content by template engine
runs:
  using: 'node12'
  main: 'index.js'