name: 'modules markdown file updater'
description: 'modules markdown file updater'
inputs:
  template_markdown_file:
    description: 'template markdown file'
    required: true
  included_markdown_url:
    description: 'included markdown files github url'
    required: true
outputs:
  # time: # id of output
  #   description: 'The time we greeted you'
  markdown:
    description: mardown content by template engine
runs:
  using: 'node12'
  main: 'index.js'