# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:
    types: [opened, deleted]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update main.md by Markdown template engin
      uses: ./.github/actions/modules-updater-action
      with:
        template_markdown_file: ./main.md
    - name: Echo main.md
      run: echo "${{ steps.package.outputs.markdown }}"
    - name : machine ls $HOME
      run : "ls -la $HOME"
    - name : machine ls -al
      working-directory : "."
      run : "ls -la"      
    - name : machine pwd
      run : "pwd"
    - name : git diff
      run : "git diff --stat --cached"